### ISSUE TITLE
KG returns 500 status for some time after initially being deployed from scratch

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-graph#1596]
We see this when we deploy renku from nothing in any ci deployment.

@lorenzo-cavazzi did this here: https://github.com/SwissDataScienceCenter/renku-ui/pull/2635

And as soon as all the pods were up and running we both logged in and saw responses from the KG like this:

```
https://renku-ci-ui-2635.dev.renku.ch/ui-server/api/kg/entities?&page=1&per_page=3&type=dataset&creator=Tasko%20Middlename%20Olevski&sort=date:desc
```

The status is 500 and the response body is:
```
{"message":"Cross-entity search failed"}
```

The logs from the kg pod is as follows:
```
2023-07-06 14:45:18,778 ERROR application - Cross-entity search failed
io.renku.http.client.RestClientError$UnexpectedResponseException: POST http://renku-ci-ui-2635-jena-master:3030/projects/sparql returned 404 Not Found; body: Error 404: Not Found
	at io.renku.http.client.RestClient$$anonfun$raiseUnexpectedResponse$1.$anonfun$applyOrElse$2(RestClient.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ io.renku.metrics.MetricsRegistry$EnabledMetricsRegistry.register(MetricsRegistry.scala:70)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at foreverM$extension @ io.renku.knowledgegraph.metrics.KGMetricsImpl.run(KGMetrics.scala:42)
	at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
	at update @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:77)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2023-07-06 14:45:18,826 ERROR application - Finding user's projects failed
io.renku.http.client.RestClientError$UnexpectedResponseException: POST http://renku-ci-ui-2635-jena-master:3030/projects/sparql returned 404 Not Found; body: Error 404: Not Found
	at io.renku.http.client.RestClient$$anonfun$raiseUnexpectedResponse$1.$anonfun$applyOrElse$2(RestClient.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ io.renku.metrics.MetricsRegistry$EnabledMetricsRegistry.register(MetricsRegistry.scala:70)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at foreverM$extension @ io.renku.knowledgegraph.metrics.KGMetricsImpl.run(KGMetrics.scala:42)
	at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
	at update @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:77)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2023-07-06 14:45:18,890 ERROR application - Cross-entity search failed
io.renku.http.client.RestClientError$UnexpectedResponseException: POST http://renku-ci-ui-2635-jena-master:3030/projects/sparql returned 404 Not Found; body: Error 404: Not Found
	at io.renku.http.client.RestClient$$anonfun$raiseUnexpectedResponse$1.$anonfun$applyOrElse$2(RestClient.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ io.renku.metrics.MetricsRegistry$EnabledMetricsRegistry.register(MetricsRegistry.scala:70)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at foreverM$extension @ io.renku.knowledgegraph.metrics.KGMetricsImpl.run(KGMetrics.scala:42)
	at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
	at update @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:77)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2023-07-06 14:45:22,046 ERROR application - Problem with gathering metrics
io.renku.http.client.RestClientError$UnexpectedResponseException: POST http://renku-ci-ui-2635-jena-master:3030/projects/sparql returned 404 Not Found; body: Error 404: Not Found
	at io.renku.http.client.RestClient$$anonfun$raiseUnexpectedResponse$1.$anonfun$applyOrElse$2(RestClient.scala:165)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ io.renku.metrics.MetricsRegistry$EnabledMetricsRegistry.register(MetricsRegistry.scala:70)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at foreverM$extension @ io.renku.knowledgegraph.metrics.KGMetricsImpl.run(KGMetrics.scala:42)
	at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1214)
	at update @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:77)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
```

**Comment by olevski** [comment]
After some time the same requests work normally.

**Comment by lorenzo-cavazzi** [comment]
This is an example of the issue in a fresh CI deployment

![Peek 2023-07-06 16-46](https://github.com/SwissDataScienceCenter/renku-graph/assets/43481553/2ed3e6b4-e08c-4810-bb1f-8a05cd8812de)
