### ISSUE TITLE
Webhook service raises an exception when there's no email on a commit fetched from GitLab

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#244]
It looks like webhook-service cannot cope with cases when there's no email on the commit data retrieved from GitLab. The service should allow either blank emails or blank usernames. In the case of blank email, a blank user node should be created. However, it's not acceptable when neither email nor username is given. In such a case, no Commit Event should be created for a commit.

Example of an exception when no email is given:
```
ch.datascience.http.client.RestClientError$MappingError: GET https://renkulab.io/gitlab/api/v4/projects/1715/repository/commits?per_page=1 returned 200 OK; error: Invalid message body: Could not decode JSON: [{"id" : "47175d629c8776337a90df5e85067bdcd4db36b1","short_id" : "47175d62","created_at" : "2019-12-28T23:03:29.000Z","parent_ids" : ["708b6f2a7aa9d8e620f944acf19e5ccea036138e"],"title" : "last update","message" : "last update\n","author_name" : "Saša Bjelić","author_email" : "","authored_date" : "2019-12-28T23:03:29.000Z","committer_name" : "Saša Bjelić","committer_email" : "","committed_date" : "2019-12-28T23:03:29.000Z"}]
	at ch.datascience.http.client.IORestClient$$anonfun$mappingError$1.applyOrElse(IORestClient.scala:119)
	at ch.datascience.http.client.IORestClient$$anonfun$mappingError$1.applyOrElse(IORestClient.scala:117)
	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:96)
	at cats.effect.internals.IOFrame$ErrorHandler.recover(IOFrame.scala:51)
	at cats.effect.internals.IOFrame$ErrorHandler.recover(IOFrame.scala:48)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:103)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:366)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:296)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1(Http1Connection.scala:189)
	at org.http4s.client.blaze.Http1Connection.$anonfun$readAndParsePrelude$1$adapted(Http1Connection.scala:188)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: [
  {
    "id" : "47175d629c8776337a90df5e85067bdcd4db36b1",
    "short_id" : "47175d62",
    "created_at" : "2019-12-28T23:03:29.000Z",
    "parent_ids" : [
      "708b6f2a7aa9d8e620f944acf19e5ccea036138e"
    ],
    "title" : "last update",
    "message" : "last update\n",
    "author_name" : "Saša Bjelić",
    "author_email" : "",
    "authored_date" : "2019-12-28T23:03:29.000Z",
    "committer_name" : "Saša Bjelić",
    "committer_email" : "",
    "committed_date" : "2019-12-28T23:03:29.000Z"
  }
]
	at org.http4s.circe.CirceInstances$.$anonfun$defaultJsonDecodeError$1(CirceInstances.scala:191)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$2(CirceInstances.scala:73)
	at scala.util.Either.fold(Either.scala:192)
	at org.http4s.circe.CirceInstances.$anonfun$jsonOfWithMedia$1(CirceInstances.scala:74)
	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:99)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
	... 24 common frames omitted
Caused by: io.circe.DecodingFailure$$anon$2: ch.datascience.graph.model.users.Email cannot be blank: DownField(author_email),DownArray
```

**Comment by rokroskar** [comment]
The better question is: how come a user in renku can be registered without an email?

**Comment by jachro** [comment]
I think this is a case when a user has no email in git config while performing a `git push`.

**Comment by rokroskar** [comment]
This should be enforced by the renku-python side as well somehow, but unclear what the mechanism should be.
