### ISSUE TITLE
Memory leak probably somewhere in the Prometheus lib

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-graph#265]
It looks there's a memory leak probably somewhere in the Prometheus lib.
```
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuffer.append(StringBuffer.java:270)
    at java.io.StringWriter.write(StringWriter.java:101)
    at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:40)
    at org.http4s.metrics.prometheus.PrometheusExportService$.$anonfun$generateResponse$1(PrometheusExportService.scala:38)
    at org.http4s.metrics.prometheus.PrometheusExportService$$$Lambda$1436/1543602907.apply
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
    at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
    at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

After some investigation, it looks the reason for that is probably an excessive creation of new threads due to overuse of the `*>` operator. As the problem mostly occurs in triples-generator, the issue will be addressed as part of #270.

**Comment by jachro** [comment]
I'm tempted to leave that investigation until the new Event Log service is in place as this could go out.
