### ISSUE TITLE
Multiple person with the same email but different gitlab ids or no gitlab ids during TRANSFORMATION

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-graph#776]
Example without one gitlab ID: vladimir.savchenko/oda-sdss
```
io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TriplesUploadResult$InvalidUpdatesFailure: Person Details Updates transformation step failed: io.renku.http.client.RestClientError$MappingException: POST http://david-renku-jena-master:3030/david/sparql returned 200 OK; error: Invalid message body: Could not decode JSON: {\"head\" : {\"vars\" : [\"resourceId\",\"name\",\"maybeEmail\",\"maybeGitLabId\",\"maybeAffiliation\"]},\"results\" : {\"bindings\" : [{\"resourceId\" : {\"type\" : \"uri\",\"value\" : \"https://david.dev.renku.ch/users/38\"},\"name\" : {\"type\" : \"literal\",\"value\" : \"Volodymyr Savchenko\"},\"maybeEmail\" : {\"type\" : \"literal\",\"value\" : \"vladimir.savchenko@gmail.com\"},\"maybeGitLabId\" : {\"type\" : \"literal\",\"datatype\" : \"http://www.w3.org/2001/XMLSchema#integer\",\"value\" : \"38\"}},{\"resourceId\" : {\"type\" : \"uri\",\"value\" : \"mailto:vladimir.savchenko@gmail.com\"},\"name\" : {\"type\" : \"literal\",\"value\" : \"Volodymyr Savchenko\"},\"maybeEmail\" : {\"type\" : \"literal\",\"value\" : \"vladimir.savchenko@gmail.com\"}}]}}; Multiple Person entities found for mailto:vladimir.savchenko@gmail.com; at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:92); at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:90); at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:106); at cats.effect.IOFiber.handleErrorWithK(IOFiber.scala:1335); at cats.effect.IOFiber.failed(IOFiber.scala:1097); at cats.effect.IOFiber.runLoop(IOFiber.scala:239); at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1175); at cats.effect.IOFiber.run(IOFiber.scala:129); at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:357)
```

and with multiple gitlab IDs : michel.chetelat/renku-at-the-bit

```
io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TriplesUploadResult$InvalidUpdatesFailure: Person Details Updates transformation step failed: io.renku.http.client.RestClientError$MappingException: POST http://david-renku-jena-master:3030/david/sparql returned 200 OK; error: Invalid message body: Could not decode JSON: {\"head\" : {\"vars\" : [\"resourceId\",\"name\",\"maybeEmail\",\"maybeGitLabId\",\"maybeAffiliation\"]},\"results\" : {\"bindings\" : [{\"resourceId\" : {\"type\" : \"uri\",\"value\" : \"https://david.dev.renku.ch/users/1034\"},\"name\" : {\"type\" : \"literal\",\"value\" : \"Gavin Lee\"},\"maybeEmail\" : {\"type\" : \"literal\",\"value\" : \"lee.gavin.k@gmail.com\"},\"maybeGitLabId\" : {\"type\" : \"literal\",\"datatype\" : \"http://www.w3.org/2001/XMLSchema#integer\",\"value\" : \"1034\"}},{\"resourceId\" : {\"type\" : \"uri\",\"value\" : \"https://david.dev.renku.ch/users/3640\"},\"name\" : {\"type\" : \"literal\",\"value\" : \"Gavin Lee\"},\"maybeEmail\" : {\"type\" : \"literal\",\"value\" : \"lee.gavin.k@gmail.com\"},\"maybeGitLabId\" : {\"type\" : \"literal\",\"datatype\" : \"http://www.w3.org/2001/XMLSchema#integer\",\"value\" : \"3640\"}}]}}; Multiple Person entities found for mailto:lee.gavin.k@gmail.com; at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:92); at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:90); at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:106); at cats.effect.IOFiber.handleErrorWithK(IOFiber.scala:1335); at cats.effect.IOFiber.failed(IOFiber.scala:1097); at cats.effect.IOFiber.runLoop(IOFiber.scala:239); at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1175); at cats.effect.IOFiber.run(IOFiber.scala:129); at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:435)
```

**Acceptance criteria:**
- [ ] read `id`, `author_name` and `author_email` from `gitlab/api/v4/projects/:id/repository/commits`;
- [ ] for all project's members read `author.id`, `author.name`, `author.username`, `push_data.commit_from`, `push_data.commit_to` from `gitlab/api/v4/users/:id/events?action=pushed`; filter by `project_id`; `commit_from` and `to` might be `null`
- [ ] merge these two groups of people by email
- [ ] replace all persons in payload with the merged persons (match by email)
- [ ] there still may be a problem that we've got a person who committed to a project but is not a member of the project anymore; in this situation we won't have this person gitlab ID; what we need to do for these people is a post upsert clean-up query which:
  - [ ] for each person having email but no gitlab ID that exists in the project
  - [ ] we go to Jena and find all persons by this person email;
  - [ ] if we find more than one, we re-link all the usages of the persons without gitlab ID to person with gitlab ID;
  - [ ] delete the persons without gitlab ID from Jena

**Comment by joke1196** [comment]
It turns out that Gavin has correctly 2 different accounts with different emails so basically we assigned a wrong email to one of his account.
