### ISSUE TITLE
Dataset  update fails because of multiple resource ids

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-graph#778]
```
2021-11-11 14:33:03,322 ERROR application - TRIPLES_GENERATED: id = e6926eae367f15aa8d3f06a121f2dc1d842171dd, projectId = 11289, projectPath: lucasdmarten/s2s-ai-competition-bootstrap Dataset Details Updates transformation step failed: java.lang.Exception: More than one resourceId found for dataset https://david.dev.renku.ch/datasets/70d636249de028b12e77cba30e82c916

io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TriplesUploadResult$InvalidUpdatesFailure: Dataset Details Updates transformation step failed: java.lang.Exception: More than one resourceId found for dataset https://david.dev.renku.ch/datasets/70d636249de028b12e77cba30e82c916

	at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:92)

	at io.renku.triplesgenerator.events.categories.triplesgenerated.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunnerImpl.scala:90)

	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:106)

	at cats.effect.IOFiber.handleErrorWithK(IOFiber.scala:1335)

	at cats.effect.IOFiber.failed(IOFiber.scala:1097)

	at cats.effect.IOFiber.runLoop(IOFiber.scala:239)

	at cats.effect.IOFiber.afterBlockingSuccessfulR(IOFiber.scala:1208)

	at cats.effect.IOFiber.run(IOFiber.scala:132)

	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:410)
```

**Comment by jachro** [comment]
Get rid of the fixing the derivation hierarchy step
